import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Quantyum",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
  openGraph: {
    title: "Quantyum - Sistema para sua empresa",
    description: "Todos os dados da sua empresa em um só lugar",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={roboto.variable}>
      <body>{children}</body>
    </html>
  );
}
